### ISSUE TITLE
Please update for CC 2015

### ISSUE THREAD

**Issue by christianmagill** [Ubertools/UberColumns#1]

**Comment by christianmagill** [comment]
Actually, the Photoshop update process says it is being removed, but it is still installed and working

**Comment by nvkzNemo** [comment]
@christianmagill Do you have Error message? Can you show me screenshot?

**Comment by christianmagill** [comment]
Creative Cloud Activity Feed shows 

The Add-on Columns installation failed because it is incompatible with installed Adobe applications. 

But everything is installed and still works perfectly!

**Comment by nvkzNemo** [comment]
Seems like it's Adobe's bug, hope they'll fix this soon.
